site_name: CERT Guide to Coordinated Vulnerability Disclosure
copyright: Copyright &copy; 2024 Carnegie Mellon University.
nav:
  - Home: 'index.md'
  - Preface: 'preface.md'
  - Executive Summary: 'executive_summary.md'
  - Introduction: 'introduction/index.md'
  - Principles:
    - Intro: 'principles/index.md'
    - Reduce Harm: 'principles/2_1.md'
    - Presume Benevolence: 'principles/2_2.md'
    - Avoid Surprise: 'principles/2_3.md'
    - Incentivize Desired Behavior: 'principles/2_4.md'
    - Ethical Considerations: 'principles/2_5.md'
    - Process Improvement: 'principles/2_6.md'
    - CVD as a Wicked Problem: 'principles/2_7.md'
  - Roles: 'roles/index.md'
  - Phases: 'phases/index.md'
  - Variation: 'variation/index.md'
  - Troubleshooting:
    - Intro: 'troubleshooting/index.md'
    - Unable to Find Vendor Contact: 'troubleshooting/6_1.md'
    - Unresponsive Vendor: 'troubleshooting/6_2.md'
    - Somebody Stops Responding: 'troubleshooting/6_3.md'
    - Leaks: 'troubleshooting/6_4.md'
    - Independent Discovery: 'troubleshooting/6_5.md'
    - Active Exploitation: 'troubleshooting/6_6.md'
    - Relationships that Go Sideways: 'troubleshooting/6_7.md'
    - Hype, Marketing, and Unwanted Attention: 'troubleshooting/6_8.md'
    - What to Do When Things Go Wrong: 'troubleshooting/6_9.md'
    - Troubleshooting CVD: 'troubleshooting/6_10.md'
  - Operations: 'operations/index.md'
  - Open Problems: 'open_problems/index.md'
  - Conclusion: 'conclusion/index.md'
  - Acknowledgements: 'acknowledgements.md'
  - Bibliography: 'bibliography.md'
  - Copyright: 'copyright.md'
  - Recent Changes: 'recent_changes.md'
  - Sightings: 'sightings.md'
dev_addr: 127.0.0.1:8002

