site_name: CERT<sup>&reg;</sup> Guide to Coordinated Vulnerability Disclosure
copyright: >
  Copyright &copy; 2017-2024 Carnegie Mellon University.
  <br/><a href="#__consent">Change cookie settings</a>

nav:
  - Home:
    - CERT Guide to CVD: 'index.md'
    - Why We Wrote This Guide: 'preface.md'
    - About This Guide: 'about.md'
  - Learning CVD:
    - Overview: 'tutorials/index.md'
    - CVD Overview:
        - A Process, Not an Event: 'tutorials/cvd_is_a_process.md'
        - CVD Terminology: 'tutorials/terminology.md'
        - Preview: 'tutorials/preview.md'
    - Executive Summary: 'tutorials/executive_summary.md'
    - CVD Problem Solving:
        - Overview: 'tutorials/troubleshooting/index.md'
        - Finding Vendor Contacts: 'tutorials/find_vendor_contact.md'
        - Unresponsive Vendor: 'tutorials/troubleshooting/unresponsive_vendor.md'
        - Somebody Stops Responding: 'tutorials/troubleshooting/somebody_stops_replying.md'
        - Leaks: 'tutorials/troubleshooting/leaks.md'
        - Independent Discovery: 'tutorials/troubleshooting/independent_discovery.md'
        - Active Exploitation: 'tutorials/troubleshooting/active_exploitation.md'
        - Relationships that Go Sideways: 'tutorials/troubleshooting/relationships_sideways.md'
        - Hype, Marketing, and Unwanted Attention: 'tutorials/troubleshooting/hype.md'
        - What to Do When Things Go Wrong: 'tutorials/troubleshooting/general_tips.md'
        - Troubleshooting CVD: 'tutorials/troubleshooting/cvd_recipes.md'
  - CVD How-To:
    - Overview: 'howto/index.md'
    - Avoid Unnecessary Risk: 'howto/avoid_risk.md'
    - Reasons to Engage a Coordinator: 'howto/coordinator_reasons.md'
    - Reduce Reporting Friction: 'howto/reduce_reporting_friction.md'
    - Report Validation: 'topics/phases/validation.md'
    - Prioritization: 'topics/phases/prioritization.md'
    - Operations:
        - Intro: 'howto/operations/index.md'
        - Monitoring: 'howto/operations/monitoring.md'
        - OpSec: 'howto/operations/opsec.md'
        - Technical Analysis: 'howto/operations/technical_analysis.md'
        - Tools: 'howto/operations/infrastructure.md'
        - Staffing: 'howto/operations/staffing.md'
    - Variation in CVD:
      - Intro: 'howto/variation/index.md'
      - Choosing a Disclosure Policy: 'howto/variation/choosing_policy.md'
      - Disclosure Choices: 'howto/variation/disclosure_choices.md'
      - Two-Party CVD: 'howto/variation/two_party_cvd.md'
      - Multi-Party CVD: 'howto/variation/mpcvd.md'
      - Response Pacing and Synchronization:  'howto/variation/response_pacing.md'
      - Maintaining Pre-Disclosure Confidentiality: 'howto/variation/maintaining_secrecy.md'
      - Disclosure Timing: 'howto/variation/disclosure_timing.md'
  - Understanding CVD:
    - Overview: 'topics/index.md'
    - Principles of CVD:
        - Intro: 'topics/principles/index.md'
        - Reduce Harm: 'topics/principles/reduce_harm.md'
        - Presume Benevolence: 'topics/principles/presume_benevolence.md'
        - Avoid Surprise: 'topics/principles/avoid_surprise.md'
        - Incentivize Desired Behavior: 'topics/principles/incentivize_behavior.md'
        - Ethical Considerations: 'topics/principles/ethics.md'
        - Process Improvement: 'topics/principles/process_improvement.md'
        - CVD as a Wicked Problem: 'topics/principles/wicked_problem.md'
    - Roles in CVD:
        - Intro: 'topics/roles/index.md'
        - Finder: 'topics/roles/finder.md'
        - Reporter: 'topics/roles/reporter.md'
        - Vendor: 'topics/roles/vendor.md'
        - Deployer: 'topics/roles/deployer.md'
        - Coordinator: 'topics/roles/coordinator.md'
        - Other Roles: 'topics/roles/other_roles.md'
    - Phases of CVD:
        - Intro: 'topics/phases/index.md'
        - Discovery: 'topics/phases/discovery.md'
        - Reporting: 'topics/phases/reporting.md'
        - Validation and Triage: 'topics/phases/validation_triage.md'
        - Remediation: 'topics/phases/remediation.md'
        - Gaining Public Awareness: 'topics/phases/public_awareness.md'
        - Promote Deployment: 'topics/phases/deployment.md'
    - Open Problems in CVD:
        - Intro: 'open_problems/index.md'
        - Vul IDs: 'open_problems/vul_ids.md'
        - IoT and CVD: 'open_problems/iot_cvd.md'
        - IoT Vul Analysis: 'appendices/iot_vul_analysis.md'
  - Reference:
    - Overview: 'reference/index.md'
    - VRF: 'reference/simple_vrf.md'
    - Advisory: 'reference/simple_advisory.md'
    - TLP: 'reference/tlp.md'
    - Disclosure Policy Templates: 'reference/disclosure_policy_templates.md'
    - Additional Resources: 'reference/additional_resources_web_vuls.md'
    - Bibliography: 'reference/bibliography.md'
  - About:
    - Conclusion: 'conclusion/index.md'
    - Acknowledgements: 'acknowledgements.md'
    - Sightings: 'sightings.md'
    - Copyright: 'copyright.md'
not_in_nav: |
  _*.md
  _*/**/*.md
theme:
  logo: 'assets/cert_seal.svg'
  name: 'material'
  features:
    - content.tabs.link
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    scheme: 'cmu'
    accent: 'red'
  icon:
    repo: fontawesome/brands/github
plugins:
  - include-markdown:
      comments: false
  - search
#  - table-reader:
#      data_path: 'data/csvs'
#  - bibtex:
#      bib_file: 'doc/md_src_files/sources_CERT-Guide-to_CVD.bib'
#  - mkdocstrings:
#      handlers:
#        python:
#          paths: [ 'src' ]
  - print-site
repo_url: 'https://github.com/CERTCC/CERT-Guide-to_CVD'
repo_name: 'CERTCC/CERT-Guide-to_CVD'
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
extra:
  analytics:
    provider: google
    property: G-87WECW6HCS
  consent:
    title: About our use of cookies on this site
    description: >-
      We use cookies to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better. 
      See our <a href="https://www.sei.cmu.edu/legal/privacy-notice/index.cfm">Privacy Notice</a> for more.
  social:
#    - icon: material/message-question
#      link: https://github.com/CERTCC/CERT-Guide-to_CVD/issues/new?template=question.md
#      name: Ask a Question
    - icon: fontawesome/solid/bug
      link: https://github.com/CERTCC/CERT-Guide-to-CVD/issues/new?template=bug_report.md
      name: Report a Problem
#    - icon: material/lightbulb-on
#      link: https://github.com/CERTCC/CERT-Guide-to_CVD/issues/new?template=feature_request.md
#      name: Request a Feature
    - icon: fontawesome/regular/comments
      link: https://github.com/CERTCC/CERT-Guide-to_CVD/discussions
      name: CERT-Guide-to_CVD Community Discussions
    - icon: fontawesome/brands/github
      link: https://github.com/CERTCC/CERT-Guide-to_CVD
      name: CERTCC/CERT-Guide-to_CVD on Github
    - icon: fontawesome/regular/envelope
      link: mailto:cert@cert.org?subject=CERT-Guide-to_CVD%20Feedback
      name: Email CERT/CC
    - icon: fontawesome/solid/house
      link: https://www.sei.cmu.edu/
      name: Software Engineering Institute
extra_javascript:
  # to render math
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # to sort tables
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
extra_css:
  - stylesheets/extra.css
watch:
  - docs
dev_addr: 127.0.0.1:8002

