site_name: CERT Guide to Coordinated Vulnerability Disclosure
copyright: Copyright &copy; 2024 Carnegie Mellon University.
nav:
  - Home:
    - CERT Guide to CVD: 'index.md'
    - Preface: 'preface.md'
    - About this Guide: 'about.md'
  - Learning CVD:
    - Overview: 'tutorials/index.md'
    - CVD Overview:
        - A Process, Not an Event: 'tutorials/cvd_is_a_process.md'
        - CVD Terminology: 'tutorials/terminology.md'
        - Preview: 'tutorials/preview.md'
    - Executive Summary: 'tutorials/executive_summary.md'
    - Troubleshooting:
        - Intro: 'troubleshooting/index.md'
        - Unable to Find Vendor Contact: 'troubleshooting/6_1.md'
        - Unresponsive Vendor: 'troubleshooting/6_2.md'
        - Somebody Stops Responding: 'troubleshooting/6_3.md'
        - Leaks: 'troubleshooting/6_4.md'
        - Independent Discovery: 'troubleshooting/6_5.md'
        - Active Exploitation: 'troubleshooting/6_6.md'
        - Relationships that Go Sideways: 'troubleshooting/6_7.md'
        - Hype, Marketing, and Unwanted Attention: 'troubleshooting/6_8.md'
        - What to Do When Things Go Wrong: 'troubleshooting/6_9.md'
        - Troubleshooting CVD: 'troubleshooting/6_10.md'
  - CVD How-To:
    - Overview: 'howto/index.md'
    - Why Coordinate?: 'tutorials/why_coordinate.md'
    - Avoid Unnecessary Risk: 'phases/avoid_risk.md'
    - Operations:
        - Intro: 'operations/index.md'
        - Tools: 'operations/tools.md'
        - OpSec: 'operations/opsec.md'
        - Staffing: 'operations/staffing.md'
    - Variation:
      - Intro: 'variation/index.md'
      - Choosing a Disclosure Policy: 'variation/choosing_policy.md'
      - Disclosure Choices: 'variation/disclosure_choices.md'
      - Two-Party CVD: 'variation/two_party_cvd.md'
      - Multi-Party CVD: 'variation/mpcvd.md'
      - Response Pacing and Synchronization:  'variation/response_pacing.md'
      - Maintaining Pre-Disclosure Confidentiality: 'variation/maintaining_secrecy.md'
      - Disclosure Timing: 'variation/disclosure_timing.md'
  - Understanding CVD:
    - Overview: 'topics/index.md'
    - Principles:
        - Intro: 'principles/index.md'
        - Reduce Harm: 'principles/2_1.md'
        - Presume Benevolence: 'principles/2_2.md'
        - Avoid Surprise: 'principles/2_3.md'
        - Incentivize Desired Behavior: 'principles/2_4.md'
        - Ethical Considerations: 'principles/2_5.md'
        - Process Improvement: 'principles/2_6.md'
        - CVD as a Wicked Problem: 'principles/2_7.md'
    - Roles:
        - Intro: 'roles/index.md'
        - Finder: 'roles/finder.md'
        - Reporter: 'roles/reporter.md'
        - Vendor: 'roles/vendor.md'
        - Deployer: 'roles/deployer.md'
        - Coordinator: 'roles/coordinator.md'
        - Other Roles: 'roles/other_roles.md'
    - Phases:
        - Intro: 'phases/index.md'
        - Discovery: 'phases/discovery.md'
        - Reporting: 'phases/reporting.md'
        - Validation and Triage: 'phases/validation_triage.md'
        - Remediation: 'phases/remediation.md'
        - Gaining Public Awareness: 'phases/public_awareness.md'
        - Promote Deployment: 'phases/deployment.md'
    - Open Problems:
        - Intro: 'open_problems/index.md'
        - Vul IDs: 'open_problems/vul_ids.md'
        - IoT and CVD: 'open_problems/iot_cvd.md'
  - Reference:
    - Overview: 'reference/index.md'
    - Bibliography: 'bibliography.md'
  - About:
    - Conclusion: 'conclusion/index.md'
    - Acknowledgements: 'acknowledgements.md'
    - Sightings: 'sightings.md'
    - Copyright: 'copyright.md'
  - Recent Changes: 'recent_changes.md'
not_in_nav: |
  _*.md
  _*/**/*.md
theme:
  logo: 'assets/cert_seal.svg'
  name: 'material'
  features:
    - content.tabs.link
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    scheme: 'cmu'
    accent: 'red'
  icon:
    repo: fontawesome/brands/github
plugins:
  - include-markdown:
      comments: false
  - search
#  - table-reader:
#      data_path: 'data/csvs'
#  - bibtex:
#      bib_file: 'doc/md_src_files/sources_CERT-Guide-to_CVD.bib'
#  - mkdocstrings:
#      handlers:
#        python:
#          paths: [ 'src' ]
  - print-site
repo_url: 'https://github.com/CERTCC/CERT-Guide-to_CVD'
repo_name: 'CERTCC/CERT-Guide-to_CVD'
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
extra:
  social:
#    - icon: material/message-question
#      link: https://github.com/CERTCC/CERT-Guide-to_CVD/issues/new?template=question.md
#      name: Ask a Question
    - icon: fontawesome/solid/bug
      link: https://github.com/CERTCC/CERT-Guide-to-CVD/issues/new?template=bug_report.md
      name: Report a Problem
#    - icon: material/lightbulb-on
#      link: https://github.com/CERTCC/CERT-Guide-to_CVD/issues/new?template=feature_request.md
#      name: Request a Feature
    - icon: fontawesome/regular/comments
      link: https://github.com/CERTCC/CERT-Guide-to_CVD/discussions
      name: CERT-Guide-to_CVD Community Discussions
    - icon: fontawesome/brands/github
      link: https://github.com/CERTCC/CERT-Guide-to_CVD
      name: CERTCC/CERT-Guide-to_CVD on Github
    - icon: fontawesome/regular/envelope
      link: mailto:cert@cert.org?subject=CERT-Guide-to_CVD%20Feedback
      name: Email CERT/CC
    - icon: fontawesome/solid/house
      link: https://www.sei.cmu.edu/
      name: Software Engineering Institute
extra_javascript:
  # to render math
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # to sort tables
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
extra_css:
  - stylesheets/extra.css
watch:
  - docs
dev_addr: 127.0.0.1:8002

